class Constants:
    # Time constants (in seconds)
    SIMULATION_INITIAL_TIME = 6 * 60 * 60  # 6:00:00 h = 21600 s
    SIMULATION_DURATION = 20 * 60 * 60  # 20:00:00 h = 72000 s

    # Event names
    START_SIMULATION = 'START_SIMULATION'
    NEXT_ARRIVAL = 'NEXT_ARRIVAL'
    END_SERVICE = 'END_SERVICE'
    END_SIMULATION = 'END_SIMULATION'

    # Operation / shift names
    RECOGIDA = "RECOGIDA"
    ENTREGA = "ENTREGA"
    DUAL = "DUAL"

    # Processor parameters
    MINIMUM_TIME_ENTREGA = 4.6
    MAXIMUM_TIME_ENTREGA = 273.87

    MINIMUM_TIME_RECOGIDA = 6.37
    MAXIMUM_TIME_RECOGIDA = 471.97

    MINIMUM_TIME_DUAL = 7.68
    MAXIMUM_TIME_DUAL = 320.73

    # Source parameters
    BETA_ENTREGA = 340
    LAMBDA_ENTREGA = 1/BETA_ENTREGA

    BETA_RECOGIDA = 360
    LAMBDA_RECOGIDA = 1/BETA_RECOGIDA

    BETA_DUAL = 475
    LAMBDA_DUAL = 1/BETA_DUAL

    # Spawn of Trucks
    MINIMUM_TRUCKS_ENTREGA = 390
    MAXIMUM_TRUCKS_ENTREGA = 637
    MEDIAN_TRUCKS_ENTREGA = 473

    MINIMUM_TRUCKS_RECOGIDA = 294
    MAXIMUM_TRUCKS_RECOGIDA = 653
    MEDIAN_TRUCKS_RECOGIDA = 471

    MINIMUM_TRUCKS_DUAL = 212
    MAXIMUM_TRUCKS_DUAL = 464
    MEDIAN_TRUCKS_DUAL = 380
